---
# tasks file for iac_role_nomad
- name: "Adicionando chave apt da HashiCorp"
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: "Instalando repositório HashiCorp"
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
    update_cache: yes
- name: "Instalando Nomad"
  apt:
    name: "nomad={{ nomad_version }}"
    state: present
- name: "Removendo arquivos padrão de exemplo"
  file:
    path: "/etc/nomad.d/{{ item }}"
    state: absent
  loop:
    - nomad.hcl
- name: "Criando o arquivo de configuração"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nomad.d/{{ item }}.tpl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0644
  loop:
    - client.hcl
    - server.hcl
- name: "Criando script de inicialização"
  template:
    src: nomad_bootstrap.sh
    dest: /usr/local/bin/nomad_bootstrap.sh
    mode: 0755

# CNI-plugin

- name: " Criando Diretorio para os plugins-CNI"
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
- name: "CNI-plugin | unarchive"
  ansible.builtin.unarchive:
    src: "{{ nomad_cni_url }}"
    dest: /opt/cni/bin
    creates: /opt/cni/bin/bridge
    remote_src: yes
    mode: "0755"
- name: " CNI sysctl"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_file: /etc/sysctl.d/10-net-bridge.conf
  loop:
    - "net.bridge.bridge-nf-call-arptables"
    - "net.bridge.bridge-nf-call-ip6tables"
    - "net.bridge.bridge-nf-call-iptables"
